name: Autoresponder Out of Office

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened]

jobs:
  auto-response:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: derekprior/add-autoresponse@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        respondableId: ${{ github.event.issue.node_id }}
        response: "🏝 OpenMoji is on hold over summer (project maintainers are out of office until Oct 2024)."
        author: ${{ github.event.issue.user.login }}
        exemptedAuthors: "carlinmack, b-g, dnlutz"
